version: '3'
services:
  postgres:
    container_name: dreadcode-db
    image: postgres:10.7-alpine
    environment:
      POSTGRES_USER: dreadcode
      POSTGRES_PASSWORD: dreadcode
      POSTGRES_DB: dreadcode
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  dreadcode_api:
    image: dreadcode_api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/dreadcode_api
    env_file:
      - .env
    depends_on:
      - postgres
volumes:
  db-data: